name: 🚀 API Gateway CI/CD

on:
  push:
    branches: ["main", "staging", "production"]
    paths:
      - 'backend/services/api-gateway/**'
      - '.github/workflows/api-gateway.yml'
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: staging

permissions:
  id-token: write
  contents: read
  packages: write
  security-events: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/reusable-microservice-build-deploy.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      service-name: api-gateway
      working-directory: backend/services/api-gateway
      dockerfile-path: backend/services/api-gateway/Dockerfile
      config-repo-config-file: environments/staging/staging-api-gateway.yaml
      helm-value-path: api-gateway.image.tag
      repo-image-name: phoenix-api-gateway-service
    secrets:
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
