name: 🚀 Booking Service CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-microservice-build-deploy.yml
    with:
      service-name: booking-service
      working-directory: backend/services/booking-service
      dockerfile-path: backend/services/booking-service/Dockerfile
      config-repo-config-file: environments/staging/staging-booking-service.yaml
      helm-value-path: booking-service.image.tag
      repo-image-name: phoenix-booking-service
      target-env: staging
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      HARBOR_URL: ${{ secrets.HARBOR_URL }}
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
